-- Starting content of the games that use question packs. Run manually in the
-- Supabase SQL Editor, after juegos.sql and lotes.sql. Safe to run again: it
-- only adds what is missing (a "Básico" pack per game and category, and its
-- items), never deletes nor duplicates anything.
--
-- Games and what an item is:
--   yo_nunca              a "Yo nunca nunca…" phrase           (4 categories)
--   quien_es_mas_probable a "¿Quién es más probable que…?"     (4 categories)
--   cuanto_me_conoces     a question about the protagonist     (4 categories)
--   tier_list             a category to rank the friends in    (suave, picante)
--   palabra_prohibida     a word to forbid                     (suave only: no categories)
--   mimica_pictionary     a word or title to act / draw        (suave only: no categories)
-- Categories are matched by name, so their ids do not matter.

-- A single statement (no temporary table), so it works however the SQL Editor
-- splits the script into transactions.
with contenido (clave, nivel, texto) as (
  values
  -- Yo nunca nunca · suave
  ('yo_nunca', 'suave', 'Yo nunca nunca he cantado en un karaoke.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca me he quedado dormido en el transporte público y me he pasado de parada.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he fingido estar al teléfono para evitar a alguien.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca me he comido algo del suelo aplicando la regla de los cinco segundos.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he visto una serie entera en un fin de semana.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he llorado con una película de animación.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he hablado solo por la calle.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca me he perdido en una ciudad usando el GPS.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he saludado a alguien que en realidad saludaba a otra persona.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he quemado la comida por estar con el móvil.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he dicho «ya voy» cuando todavía estaba en casa.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca me he caído en público.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he enviado un mensaje al chat equivocado.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he comido pizza fría para desayunar.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he bailado delante del espejo.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he olvidado el cumpleaños de un amigo.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he hecho una foto a mi comida antes de comérmela.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca me he quedado encerrado en un baño.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he aprendido una coreografía de internet.'),
  ('yo_nunca', 'suave', 'Yo nunca nunca he roto algo y he disimulado que no fui yo.'),
  -- Yo nunca nunca · secretos
  ('yo_nunca', 'secretos', 'Yo nunca nunca he leído los mensajes de otra persona sin permiso.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he regalado algo que me habían regalado a mí.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he mentido sobre mi edad.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he stalkeado a un ex en redes sociales.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he fingido estar enfermo para no ir a clase o al trabajo.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he contado un secreto que me pidieron guardar.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he dejado a alguien en visto a propósito.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he cotilleado sobre alguien de esta sala.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he usado la cuenta de streaming de otra persona sin que lo sepa.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he copiado en un examen.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he puesto una excusa falsa para cancelar un plan.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he borrado un mensaje antes de que lo leyeran.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he fingido que me gustaba un regalo.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he buscado mi propio nombre en internet.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca me he inventado una anécdota para quedar bien.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he escuchado una conversación ajena a escondidas.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he comido algo de la nevera que no era mío.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he fingido saber de un tema para no quedar mal.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he tenido una cuenta secreta en redes sociales.'),
  ('yo_nunca', 'secretos', 'Yo nunca nunca he culpado a otra persona de algo que hice yo.'),
  -- Yo nunca nunca · picante
  ('yo_nunca', 'picante', 'Yo nunca nunca he besado a alguien que acababa de conocer.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he tenido una cita a ciegas.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he enviado un mensaje subido de tono.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca me he liado con alguien de mi grupo de amigos.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he usado una aplicación de citas.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he besado a dos personas en la misma noche.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he vuelto con un ex.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he tenido un crush con alguien de esta sala.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he ligado en una boda.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he mentido para conseguir una cita.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca me he enamorado de alguien que tenía pareja.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he dado un beso en un lugar público con mucha gente mirando.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he escrito a un ex de madrugada.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he tenido una relación a distancia.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he ligado con alguien por mensajes sin conocerlo en persona.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he dado mi número a un desconocido en una fiesta.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca me he arrepentido de un beso.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he tenido un rollo de verano.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he ignorado a alguien que me gustaba para hacerme el interesante.'),
  ('yo_nunca', 'picante', 'Yo nunca nunca he soñado con alguien de esta sala.'),
  -- Yo nunca nunca · sobre el grupo
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca me he enfadado con alguien de esta sala sin que lo supiera.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he hablado mal de un plan del grupo y luego me lo he pasado genial.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he silenciado el grupo de WhatsApp.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he llegado el último a un plan del grupo.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he guardado un secreto de alguien de esta sala.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he contado a otra persona algo que pasó en el grupo.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he tenido una foto vergonzosa de alguien de esta sala.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he cancelado un plan del grupo en el último momento.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he pensado que alguien de esta sala hace trampas en los juegos.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he leído el grupo sin contestar durante horas.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he hecho una captura de algo que se dijo en el grupo.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he pedido dinero prestado a alguien de esta sala y he tardado en devolverlo.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca me he reído de un chiste del grupo sin entenderlo.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he imitado a alguien de esta sala a sus espaldas.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he defendido a alguien de esta sala sin que se enterase.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he tenido envidia de un plan que el grupo hizo sin mí.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he cogido ropa prestada a alguien de esta sala.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he puesto un mote secreto a alguien de esta sala.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he votado en contra de un plan y luego he sido el que más ha disfrutado.'),
  ('yo_nunca', 'sobre el grupo', 'Yo nunca nunca he soñado con un viaje con todo el grupo.'),

  -- ¿Quién es más probable? · suave
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que llegue tarde a su propia boda?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que se haga famoso en internet?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que se pierda en un aeropuerto?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que adopte diez gatos?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que se ría en un momento serio?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que se olvide las llaves dentro de casa?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que gane un concurso de la tele?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que sobreviva a un apocalipsis zombi?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que se quede dormido en el cine?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que monte un negocio de éxito?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que coma lo mismo toda la semana?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que empiece a bailar sin música?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que se apunte al gimnasio y no vaya nunca?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que se vaya a vivir a otro país?'),
  ('quien_es_mas_probable', 'suave', '¿Quién es más probable que llore viendo un anuncio?'),
  -- ¿Quién es más probable? · secretos
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que tenga un diario secreto?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que haya mentido hoy a alguien de esta sala?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que lea los mensajes y no conteste?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que tenga una cuenta secreta en redes?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que no sepa guardar un secreto?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que finja que le gusta un regalo?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que cotillee el móvil de otra persona?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que tenga una canción vergonzosa en bucle?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que se invente una excusa para no salir?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que haya stalkeado a alguien esta semana?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que esconda chuches en su cuarto?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que sepa los cotilleos de todo el mundo?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que haya llorado este mes?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que tenga capturas de todo?'),
  ('quien_es_mas_probable', 'secretos', '¿Quién es más probable que haya copiado en un examen?'),
  -- ¿Quién es más probable? · picante
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que se lie con alguien esta noche?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que tenga más ligues en el móvil?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que vuelva con su ex?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que tenga una cita esta semana?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que envíe un mensaje atrevido y se arrepienta?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que se enamore en un viaje?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que ligue en una boda?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que tenga un crush secreto en esta sala?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que se case primero?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que tenga la mejor frase para ligar?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que haga un baile sensual en una fiesta?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que use tres aplicaciones de citas a la vez?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que se ponga rojo con una pregunta picante?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que tenga una cita desastrosa?'),
  ('quien_es_mas_probable', 'picante', '¿Quién es más probable que se líe con alguien famoso?'),
  -- ¿Quién es más probable? · sobre el grupo
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que organice el próximo viaje del grupo?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que cancele el próximo plan?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que se duerma primero en una fiesta?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que pague la cuenta sin decir nada?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que haga trampas en este juego?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que mande un audio de cinco minutos al grupo?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que se olvide de un plan que propuso él mismo?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que haga las mejores fotos del grupo?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que sea el último en irse de una fiesta?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que acabe cocinando para todos?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que discuta por una tontería?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que recuerde todas las anécdotas del grupo?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que se pierda volviendo a casa?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que proponga el plan más loco?'),
  ('quien_es_mas_probable', 'sobre el grupo', '¿Quién es más probable que siga siendo amigo de todos dentro de veinte años?'),

  -- ¿Cuánto me conoces? · suave
  ('cuanto_me_conoces', 'suave', '¿Cuál es mi comida favorita?'),
  ('cuanto_me_conoces', 'suave', '¿Qué serie vería una y otra vez?'),
  ('cuanto_me_conoces', 'suave', '¿Cuál es mi color favorito?'),
  ('cuanto_me_conoces', 'suave', '¿Qué haría con un día libre sin planes?'),
  ('cuanto_me_conoces', 'suave', '¿Qué superpoder elegiría?'),
  ('cuanto_me_conoces', 'suave', '¿Qué animal sería?'),
  ('cuanto_me_conoces', 'suave', '¿A qué país me iría de viaje mañana mismo?'),
  ('cuanto_me_conoces', 'suave', '¿Qué canción pongo cuando nadie me ve?'),
  ('cuanto_me_conoces', 'suave', '¿Cuál es mi bebida favorita?'),
  ('cuanto_me_conoces', 'suave', '¿Qué comida no soporto?'),
  ('cuanto_me_conoces', 'suave', '¿Cuál fue mi primer móvil o consola?'),
  ('cuanto_me_conoces', 'suave', '¿Qué es lo primero que hago al despertarme?'),
  ('cuanto_me_conoces', 'suave', '¿Cuál es mi película favorita?'),
  ('cuanto_me_conoces', 'suave', '¿Qué trabajo tendría en otra vida?'),
  ('cuanto_me_conoces', 'suave', '¿Qué es lo que más me hace reír?'),
  -- ¿Cuánto me conoces? · secretos
  ('cuanto_me_conoces', 'secretos', '¿Cuál es mi mayor miedo?'),
  ('cuanto_me_conoces', 'secretos', '¿Qué manía rara tengo?'),
  ('cuanto_me_conoces', 'secretos', '¿De qué me arrepiento más?'),
  ('cuanto_me_conoces', 'secretos', '¿Qué es lo que más me enfada?'),
  ('cuanto_me_conoces', 'secretos', '¿Qué guardo como recuerdo aunque no sirva para nada?'),
  ('cuanto_me_conoces', 'secretos', '¿Qué placer culpable tengo?'),
  ('cuanto_me_conoces', 'secretos', '¿Cuál ha sido mi momento más vergonzoso?'),
  ('cuanto_me_conoces', 'secretos', '¿Qué es lo que nunca le contaría a mis padres?'),
  ('cuanto_me_conoces', 'secretos', '¿Qué sueño tengo y casi nunca digo?'),
  ('cuanto_me_conoces', 'secretos', '¿Qué excusa uso más para no hacer algo?'),
  -- ¿Cuánto me conoces? · picante
  ('cuanto_me_conoces', 'picante', '¿Qué es lo primero que me fijo en alguien que me gusta?'),
  ('cuanto_me_conoces', 'picante', '¿Cuál sería mi cita perfecta?'),
  ('cuanto_me_conoces', 'picante', '¿Qué famoso es mi crush?'),
  ('cuanto_me_conoces', 'picante', '¿Cuántas relaciones serias he tenido?'),
  ('cuanto_me_conoces', 'picante', '¿Qué es lo que más me atrae de una persona?'),
  ('cuanto_me_conoces', 'picante', '¿Cuál es mi peor costumbre cuando ligo?'),
  ('cuanto_me_conoces', 'picante', '¿Dónde fue mi primer beso?'),
  ('cuanto_me_conoces', 'picante', '¿Qué canción pondría en una cita?'),
  ('cuanto_me_conoces', 'picante', '¿Qué es lo que no soporto en una cita?'),
  ('cuanto_me_conoces', 'picante', '¿Cómo ligo: directo o lanzando indirectas?'),
  -- ¿Cuánto me conoces? · sobre el grupo
  ('cuanto_me_conoces', 'sobre el grupo', '¿Con quién de la sala me iría de viaje?'),
  ('cuanto_me_conoces', 'sobre el grupo', '¿Cuál es mi recuerdo favorito con el grupo?'),
  ('cuanto_me_conoces', 'sobre el grupo', '¿A quién de la sala llamaría para una emergencia?'),
  ('cuanto_me_conoces', 'sobre el grupo', '¿Quién de la sala creo que me conoce mejor?'),
  ('cuanto_me_conoces', 'sobre el grupo', '¿Qué plan del grupo repetiría mañana?'),
  ('cuanto_me_conoces', 'sobre el grupo', '¿Qué apodo me pondría el grupo?'),
  ('cuanto_me_conoces', 'sobre el grupo', '¿Quién de la sala me hace reír más?'),
  ('cuanto_me_conoces', 'sobre el grupo', '¿Cuándo conocí a la mayoría del grupo?'),
  ('cuanto_me_conoces', 'sobre el grupo', '¿Qué rol tengo en el grupo?'),
  ('cuanto_me_conoces', 'sobre el grupo', '¿Qué cambiaría de los planes del grupo?'),

  -- Tier list de amigos · suave
  ('tier_list', 'suave', 'El que mejor cocina'),
  ('tier_list', 'suave', 'El más tacaño'),
  ('tier_list', 'suave', 'El que peor conduce'),
  ('tier_list', 'suave', 'El más puntual'),
  ('tier_list', 'suave', 'El que mejor baila'),
  ('tier_list', 'suave', 'El más dormilón'),
  ('tier_list', 'suave', 'El que tiene mejor gusto musical'),
  ('tier_list', 'suave', 'El que mejor guarda un secreto'),
  ('tier_list', 'suave', 'El más dramático'),
  ('tier_list', 'suave', 'El que sobreviviría más en una isla desierta'),
  ('tier_list', 'suave', 'El más despistado'),
  ('tier_list', 'suave', 'El que mejor cuenta los chistes'),
  ('tier_list', 'suave', 'El que más tarda en contestar los mensajes'),
  ('tier_list', 'suave', 'El que mejor viste'),
  ('tier_list', 'suave', 'El más competitivo'),
  ('tier_list', 'suave', 'El que más se queja'),
  ('tier_list', 'suave', 'El mejor organizando planes'),
  ('tier_list', 'suave', 'El más friki'),
  ('tier_list', 'suave', 'El que más come'),
  ('tier_list', 'suave', 'El más cariñoso'),
  -- Tier list de amigos · picante
  ('tier_list', 'picante', 'El que más liga'),
  ('tier_list', 'picante', 'El que tiene peor gusto para la pareja'),
  ('tier_list', 'picante', 'El más ligón por mensajes'),
  ('tier_list', 'picante', 'El que mejor besa (según la leyenda)'),
  ('tier_list', 'picante', 'El más celoso'),
  ('tier_list', 'picante', 'El que más tarda en superar a un ex'),
  ('tier_list', 'picante', 'El que tiene las mejores anécdotas de citas'),
  ('tier_list', 'picante', 'El más romántico'),
  ('tier_list', 'picante', 'El que más fiesta aguanta'),
  ('tier_list', 'picante', 'El que peor gestiona la resaca'),

  -- Palabra prohibida (sin categorías)
  ('palabra_prohibida', 'suave', 'sí'), ('palabra_prohibida', 'suave', 'no'), ('palabra_prohibida', 'suave', 'vale'),
  ('palabra_prohibida', 'suave', 'tío'), ('palabra_prohibida', 'suave', 'bueno'), ('palabra_prohibida', 'suave', 'pues'),
  ('palabra_prohibida', 'suave', 'bebida'), ('palabra_prohibida', 'suave', 'beber'), ('palabra_prohibida', 'suave', 'yo'),
  ('palabra_prohibida', 'suave', 'móvil'), ('palabra_prohibida', 'suave', 'macarrones'), ('palabra_prohibida', 'suave', 'juego'),
  ('palabra_prohibida', 'suave', 'nada'), ('palabra_prohibida', 'suave', 'mucho'), ('palabra_prohibida', 'suave', 'siempre'),
  ('palabra_prohibida', 'suave', 'nunca'), ('palabra_prohibida', 'suave', 'hola'), ('palabra_prohibida', 'suave', 'gracias'),
  ('palabra_prohibida', 'suave', 'perdón'), ('palabra_prohibida', 'suave', 'literal'), ('palabra_prohibida', 'suave', 'en plan'),
  ('palabra_prohibida', 'suave', 'o sea'), ('palabra_prohibida', 'suave', 'de verdad'), ('palabra_prohibida', 'suave', 'mira'),
  ('palabra_prohibida', 'suave', 'oye'), ('palabra_prohibida', 'suave', 'venga'), ('palabra_prohibida', 'suave', 'ya'),
  ('palabra_prohibida', 'suave', 'qué'), ('palabra_prohibida', 'suave', 'cómo'), ('palabra_prohibida', 'suave', 'porque'),
  ('palabra_prohibida', 'suave', 'hora'), ('palabra_prohibida', 'suave', 'casa'), ('palabra_prohibida', 'suave', 'comida'),
  ('palabra_prohibida', 'suave', 'fiesta'), ('palabra_prohibida', 'suave', 'música'), ('palabra_prohibida', 'suave', 'mañana'),
  ('palabra_prohibida', 'suave', 'ayer'), ('palabra_prohibida', 'suave', 'hoy'), ('palabra_prohibida', 'suave', 'dinero'),
  ('palabra_prohibida', 'suave', 'trabajo'), ('palabra_prohibida', 'suave', 'clase'), ('palabra_prohibida', 'suave', 'nombre'),
  ('palabra_prohibida', 'suave', 'amigo'), ('palabra_prohibida', 'suave', 'gente'), ('palabra_prohibida', 'suave', 'vaso'),
  ('palabra_prohibida', 'suave', 'agua'), ('palabra_prohibida', 'suave', 'cerveza'), ('palabra_prohibida', 'suave', 'hielo'),
  ('palabra_prohibida', 'suave', 'mesa'), ('palabra_prohibida', 'suave', 'baño'), ('palabra_prohibida', 'suave', 'calor'),
  ('palabra_prohibida', 'suave', 'frío'), ('palabra_prohibida', 'suave', 'genial'), ('palabra_prohibida', 'suave', 'guay'),
  ('palabra_prohibida', 'suave', 'flipante'), ('palabra_prohibida', 'suave', 'obvio'), ('palabra_prohibida', 'suave', 'claro'),
  ('palabra_prohibida', 'suave', 'exacto'), ('palabra_prohibida', 'suave', 'jaja'), ('palabra_prohibida', 'suave', 'madre mía'),

  -- Mímica o Pictionary (sin categorías)
  ('mimica_pictionary', 'suave', 'Titanic'), ('mimica_pictionary', 'suave', 'El Rey León'), ('mimica_pictionary', 'suave', 'Harry Potter'),
  ('mimica_pictionary', 'suave', 'Star Wars'), ('mimica_pictionary', 'suave', 'Buscando a Nemo'), ('mimica_pictionary', 'suave', 'Spider-Man'),
  ('mimica_pictionary', 'suave', 'Shrek'), ('mimica_pictionary', 'suave', 'Jurassic Park'), ('mimica_pictionary', 'suave', 'Frozen'),
  ('mimica_pictionary', 'suave', 'Toy Story'), ('mimica_pictionary', 'suave', 'Piratas del Caribe'), ('mimica_pictionary', 'suave', 'El Señor de los Anillos'),
  ('mimica_pictionary', 'suave', 'Super Mario'), ('mimica_pictionary', 'suave', 'Pokémon'), ('mimica_pictionary', 'suave', 'Tetris'),
  ('mimica_pictionary', 'suave', 'Minecraft'), ('mimica_pictionary', 'suave', 'Fortnite'), ('mimica_pictionary', 'suave', 'Pac-Man'),
  ('mimica_pictionary', 'suave', 'astronauta'), ('mimica_pictionary', 'suave', 'cohete'), ('mimica_pictionary', 'suave', 'macarrón'),
  ('mimica_pictionary', 'suave', 'pizza'), ('mimica_pictionary', 'suave', 'helado'), ('mimica_pictionary', 'suave', 'paella'),
  ('mimica_pictionary', 'suave', 'cocinero'), ('mimica_pictionary', 'suave', 'bombero'), ('mimica_pictionary', 'suave', 'dentista'),
  ('mimica_pictionary', 'suave', 'peluquero'), ('mimica_pictionary', 'suave', 'socorrista'), ('mimica_pictionary', 'suave', 'mago'),
  ('mimica_pictionary', 'suave', 'pirata'), ('mimica_pictionary', 'suave', 'vampiro'), ('mimica_pictionary', 'suave', 'zombi'),
  ('mimica_pictionary', 'suave', 'fantasma'), ('mimica_pictionary', 'suave', 'robot'), ('mimica_pictionary', 'suave', 'dinosaurio'),
  ('mimica_pictionary', 'suave', 'elefante'), ('mimica_pictionary', 'suave', 'canguro'), ('mimica_pictionary', 'suave', 'pingüino'),
  ('mimica_pictionary', 'suave', 'mono'), ('mimica_pictionary', 'suave', 'serpiente'), ('mimica_pictionary', 'suave', 'gato'),
  ('mimica_pictionary', 'suave', 'perro'), ('mimica_pictionary', 'suave', 'tiburón'), ('mimica_pictionary', 'suave', 'pulpo'),
  ('mimica_pictionary', 'suave', 'bicicleta'), ('mimica_pictionary', 'suave', 'avión'), ('mimica_pictionary', 'suave', 'submarino'),
  ('mimica_pictionary', 'suave', 'tren'), ('mimica_pictionary', 'suave', 'patinete'), ('mimica_pictionary', 'suave', 'globo'),
  ('mimica_pictionary', 'suave', 'paraguas'), ('mimica_pictionary', 'suave', 'gafas de sol'), ('mimica_pictionary', 'suave', 'cepillo de dientes'),
  ('mimica_pictionary', 'suave', 'karaoke'), ('mimica_pictionary', 'suave', 'bolos'), ('mimica_pictionary', 'suave', 'surf'),
  ('mimica_pictionary', 'suave', 'boxeo'), ('mimica_pictionary', 'suave', 'yoga'), ('mimica_pictionary', 'suave', 'esquiar'),
  ('mimica_pictionary', 'suave', 'pescar'), ('mimica_pictionary', 'suave', 'hacer la compra'), ('mimica_pictionary', 'suave', 'cambiar un pañal'),
  ('mimica_pictionary', 'suave', 'hacerse un selfie'), ('mimica_pictionary', 'suave', 'perder el autobús'), ('mimica_pictionary', 'suave', 'pedir un taxi'),
  ('mimica_pictionary', 'suave', 'montar un mueble'), ('mimica_pictionary', 'suave', 'freír un huevo'), ('mimica_pictionary', 'suave', 'tender la ropa'),
  ('mimica_pictionary', 'suave', 'volcán'), ('mimica_pictionary', 'suave', 'arcoíris'), ('mimica_pictionary', 'suave', 'tormenta'),
  ('mimica_pictionary', 'suave', 'castillo'), ('mimica_pictionary', 'suave', 'faro'), ('mimica_pictionary', 'suave', 'pirámide'),
  ('mimica_pictionary', 'suave', 'Torre Eiffel'), ('mimica_pictionary', 'suave', 'Estatua de la Libertad'), ('mimica_pictionary', 'suave', 'Papá Noel'),
  ('mimica_pictionary', 'suave', 'Michael Jackson'), ('mimica_pictionary', 'suave', 'Pepe la rana'), ('mimica_pictionary', 'suave', 'Pikachu')
),
-- A "Básico" pack for every game and category used above (if missing).
nuevos_lotes as (
  insert into public.lotes (juego_id, nivel_id, nombre)
  select distinct j.id, n.id, 'Básico'
  from contenido c
  join public.juegos j on j.clave = c.clave
  join public.niveles n on n.nombre = c.nivel
  on conflict (juego_id, nivel_id, nombre) do nothing
  returning id, juego_id, nivel_id
)
-- Their items. Packs created just above are not visible yet to this same
-- statement, hence nuevos_lotes; juego_id / nivel_id come from the pack (trigger).
insert into public.preguntas (texto, lote_id, tipo)
select c.texto, coalesce(nl.id, l.id), null
from contenido c
join public.juegos j on j.clave = c.clave
join public.niveles n on n.nombre = c.nivel
left join nuevos_lotes nl on nl.juego_id = j.id and nl.nivel_id = n.id
left join public.lotes l on l.juego_id = j.id and l.nivel_id = n.id and l.nombre = 'Básico'
where coalesce(nl.id, l.id) is not null
on conflict (lote_id, texto) do nothing;
